=== fantasticlab/fantastic-jdbc/fantastic-jdbc-core/src/main/resources/mybatis-3-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT configuration (properties?, dataSource?, mappers?)>

<!ELEMENT properties (property*)>
<!ATTLIST properties
resource CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT dataSource (property*)>
<!ATTLIST dataSource
type CDATA #IMPLIED
>

<!ELEMENT mappers (mapper*,package*)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper
resource CDATA #IMPLIED
url CDATA #IMPLIED
class CDATA #IMPLIED
>

<!ELEMENT package EMPTY>
<!ATTLIST package
name CDATA #REQUIRED
>

=== fantasticlab/fantastic-jdbc/fantastic-jdbc-core/src/main/resources/JdbcConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--<!DOCTYPE configuration>-->

<!DOCTYPE configuration
        PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
        "mybatis-3-config.dtd">

<configuration>

    <properties resource="conf.properties">
        <property name="project_name" value="fantastic-jdbc"/>
    </properties>

    <dataSource>
        <property name="driver" value="com.mysql.cj.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf8"/>
        <property name="username" value="root"/>
        <property name="password" value="123"/>
    </dataSource>

    <mappers>
        <mapper class="com.github.fantasticlab.jdbc.test.dao.UserMapper" resource="mappers/UserMapper.xml"/>
    </mappers>

</configuration>
